version: "3.0"

services:
  nginx:
    build: ./docker-nginx
    image: ngnx
    depends_on:
      - app
    ports:
      - 80:80
    restart: always
  app:
    build: .
    image: weblanches
    ports:
      - 8080:8080